package database;
// Generated May 13, 2016 8:31:21 PM by Hibernate Tools 4.3.1

import abstracts.ACustomers;
import functions.Database;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;




/**
 * Customers generated by hbm2java
 */
public class Customers extends ACustomers implements java.io.Serializable {

    public Customers() 
    {
    }

    public Customers(String firstname, String lastname, String phone) 
    {
       this.firstname = firstname;
       this.lastname = lastname;
       this.phone = phone;
    }
    private Customers(CustomerBuilder builder) 
    {
       this.firstname = builder.firstname;
       this.lastname = builder.lastname;
       this.phone = builder.phone;
    }
    public Object[] toArray()
    {
        Vector vector = new Vector();
        vector.add(cid);
        vector.add(firstname);
        vector.add(lastname);
        vector.add(phone);
        return vector.toArray();
    }
    public static class CustomerBuilder
    {
        public String firstname;
        public String lastname;
        public String phone;  
        public CustomerBuilder firstname(String firstname)
        {
            this.firstname = firstname;
            return this;
        }
        public CustomerBuilder lastname(String lastname)
        {
            this.lastname = lastname;
            return this;
        }
        public CustomerBuilder phone(String phone)
        {
            this.phone = phone;
            return this;
        }
        public Customers build()
        {
            return new Customers(this);
        }
    }
    public List<Customers> getCustomerList(JComboBox combobox,Database db,int aid)
    {  
        List<Customers> customersList = db.getList(Customers.class);
        int listSize = customersList.size();
        List<String> customers = new ArrayList<String>();
        int index = -1;
        if(listSize > 0)
        {
            Iterator iterator = customersList.iterator();
            while(iterator.hasNext())
            {
                Customers c = (Customers)iterator.next();
                String name = c.getFirstname() + " " + c.getLastname();
                customers.add(name);
                if(aid > 0)
                {
                    if(aid == c.getCid())
                    {
                        index = customers.size() - 1 ;
                    }
                }
            }
            combobox.setModel(new DefaultComboBoxModel(customers.toArray()));
        }
        combobox.setSelectedIndex(index);
        return customersList;
    }
    public void getCustomerDetails(List<Customers> list,JTable table)
    {
        if(list!=null && list.size() > 0)
        {
            Vector vector = new Vector(list);
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            Enumeration e = vector.elements();
            while(e.hasMoreElements())
            {
                Customers customer = (Customers)e.nextElement();
                model.addRow(customer.toArray());
            }
            table.setModel(model); 
            table.getTableHeader().setReorderingAllowed(false);
            table.setAutoCreateRowSorter(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Kayıtlı müşteri bulunmamaktadır.");
        }
    }
}


