package database;
// Generated May 13, 2016 8:31:21 PM by Hibernate Tools 4.3.1

import abstracts.AUsers;
import interfaces.IUsers;





/**
 * Users generated by hbm2java
 */
public class Users extends AUsers implements java.io.Serializable {


    public Users() 
    {
    }

    public Users(String id, String password) 
    {
       this.id = id;
       this.password = password;
    }
    private Users(UserBuilder builder) 
    {
        this.id = builder.id;
        this.password = builder.password;
    }
    public static class UserBuilder
    {
        private String id;
        private String password;
        public UserBuilder id(String id)
        {
            this.id = id;
            return this;
        }
        public UserBuilder password(String password)
        {
            this.password = password;
            return this;
        }
        public Users build()
        {
            return new Users(this);
        }
    }

}


